services:
  db:
    image: postgres:16
    container_name: tf_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-teamfinder}
      POSTGRES_USER: ${POSTGRES_USER:-teamfinder}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teamfinder}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-teamfinder} -d ${POSTGRES_DB:-teamfinder}"]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
