
version: "3.9"
services:
  db:
    image: postgres:15
    env_file: [.env]
    ports: ["5432:5432"]
    volumes:
      - ./sql/initdb:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-teamfinder}"]
      interval: 5s
      timeout: 5s
      retries: 20
  api:
    build: .
    env_file: [.env]
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes:
      - ./app:/app/app
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--reload"]
  adminer:
    image: adminer:4
    ports: ["8080:8080"]
    depends_on: [db]
